### ISSUE TITLE
The database is not found when running test when package is installed.

### ISSUE THREAD

**Issue by 183amir** [bioidiap/bob.db.casme2#4]
In here: https://github.com/bioidiap/bob.db.casme2/blob/master/bob/db/casme2/test.py#L105
It is assumed that package is being tested in its git repo. However, this will not work when package gets installed first and then tested which is what happens in conda builds.

```
===== testing package: bob.db.casme2-2.0.4-py27_0 =====
import: 'bob'
import: 'bob.db'
import: 'bob.db.casme2'
===== bob.db.casme2-2.0.4-py27_0 OK =====
+ bob_dbmanage.py casme2 download
Skipping download of file '/opt/conda/envs/_test/lib/python2.7/site-packages/bob/db/casme2/db.sql3' since it exists already.
+ nosetests -sv bob.db.casme2
Failure: SkipTest (The database file './bob/db/casme2/db.sql3' is not available; did you forget to run 'bob_dbmanage.py casme2 create' ?) ... SKIP: The database file './bob/db/casme2/db.sql3' is not available; did you forget to run 'bob_dbmanage.py casme2 create' ?
```
Full log: https://circleci.com/gh/conda-forge/staged-recipes/2263

P.S. Please do not tell me to submit a PR for this. I am already spending a lot of time finding these bugs during the conda packaging process.

This bug was discovered here: https://github.com/conda-forge/staged-recipes/pull/434

**Comment by siebenkopf** [comment]
Yes, it is checking for the file in the wrong location. Try to use ``pkg_resources.resource_filename``.

**Comment by tiagofrepereira2012** [comment]
I will take care this tomorrow.
Have an exam tomorrow
